# Generated by Django 2.2.5 on 2019-11-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='headshot',
            field=models.ImageField(upload_to='headshots', verbose_name='Headshot'),
        ),
    ]
