# Generated by Django 2.2.5 on 2019-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0005_auto_20191112_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='abstract',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='bio',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='headshots', verbose_name='Headshot'),
        ),
    ]
