# Generated by Django 2.2.5 on 2019-11-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0007_auto_20191112_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='media/headshots/', verbose_name='Headshot'),
        ),
    ]
