# Generated by Django 2.2.5 on 2019-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Seminar Date')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('abstract', models.CharField(max_length=10000, verbose_name='Abstract')),
                ('headshot', models.BinaryField(verbose_name='Headshot')),
            ],
        ),
    ]
