# Generated by Django 2.2.5 on 2019-11-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0002_auto_20191112_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='presenter',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
