# Generated by Django 2.2.5 on 2019-11-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0003_seminar_presenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='bio',
            field=models.CharField(default='', max_length=10000, verbose_name='Abstract'),
            preserve_default=False,
        ),
    ]
