# Generated by Django 2.2.5 on 2019-11-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0004_seminar_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='bio',
            field=models.CharField(max_length=10000, verbose_name='Biography'),
        ),
    ]
