# Generated by Django 2.2.5 on 2019-11-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0006_auto_20191112_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='headshots/', verbose_name='Headshot'),
        ),
    ]
