# Generated by Django 2.2.5 on 2019-11-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_cal', '0008_auto_20191112_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='headshots/', verbose_name='Headshot'),
        ),
    ]
